# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Create OIIO binaries

on: [push]

jobs:
  build:
    name: Building OIIO Linux binaries
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: install conan
      run: |
        pip install conan
        conan --version
        pip install wheel
    - name: remove OpenExr
      run: |
        apt list --installed
        sudo apt-get remove --purge libopenexr-dev
        sudo apt-get remove --purge libopenexr24
    - name: setup conan profile
      run: |
        conan profile new default --detect
        conan profile update settings.compiler.libcxx=libstdc++11 default
    - name: Building
      run: |
        ./run_linux.sh
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: buildpy/pythonwheel/dist/*

  publish:
    name: Publish OIIO Linux binaries
    runs-on: ubuntu-20.04
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: my-artifact
    - name: Display structure of downloaded files
      run: ls -R
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload release binaries
      uses: alexellis/upload-assets@0.2.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        asset_paths: '["*.whl"]'

