# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Create OIIO binaries

on: [push]

jobs:
  deploy:

    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: install conan
      run: |
        pip install conan
        conan --version
        pip install wheel
    - name: Building
      run: |
        ./run_linux.sh
