# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Create OIIO binaries

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: install conan
      run: |
        pip install conan
        conan --version
        pip install wheel
    - name: remove OpenExr
      run: |
        apt list --installed
        sudo apt-get remove --purge libopenexr-dev
        sudo apt-get remove --purge libopenexr24
    - name: setup conan profile
      run: |
        conan profile new default --detect
        conan profile update settings.compiler.libcxx=libstdc++11 default
    - name: Building
      run: |
        ./run_linux.sh
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: '["./buildpy/pythonwheel/dist/*"]'
